<?php
/**
 * @var \Zend\View\Renderer\PhpRenderer $this
 * @var \Omeka\Api\Representation\AbstractResourceEntityRepresentation $resource
 */

$this->htmlElement('body')->appendAttribute('class', 'mirador play');
$title = $resource->displayTitle();
$creator = $resource->value('dcterms:creator', ['type' => 'literal']);
if ($creator) {
    $title .= ' - ' . $creator;
}

echo $this->pageTitle($title);
?>

<?php echo $this->mirador($resource);
