<?php
/**
 * @var \Laminas\View\Renderer\PhpRenderer $this
 * @var \Mirador\Site\BlockLayout\Mirador $block
 * @var \Omeka\Api\Representation\SiteBlockAttachmentRepresentation[] $attachments
 */

$resources = [];
foreach ($attachments as $attachment) {
    $item = $attachment->item();
    if ($item) {
        $resources[] = $item;
    }
}
// Display the viewer with the specified resources.
echo $this->mirador($resources);
