<?php
/**
 * @var \Zend\View\Renderer\PhpRenderer $this
 * @var string $style
 * @var string $class
 * @var array $config
 *
 * @link https://github.com/ProjectMirador/mirador/wiki/Configuration-Guides
 */
?>

<div id="<?= $config['id'] ?>" style="<?= $style ?>" class="<?= $class ?>" allowfullscreen="allowfullscreen"></div>
<script type="text/javascript">
    $(function() {
        Mirador(<?= json_encode($config) ?>);
    });
</script>
