<?php
/**
 * @var \Laminas\View\Renderer\PhpRenderer $this
 * @var array $plugins
 */

// Currently, with Mirador 3, plugins should be included and compiled with the
// bundle, so they are not available separately.
// So this helper is used only to include special extra css or js that may be needed.
// See file mirador-2-plugins for a plugin that can be managed via a simple reference in the header.
// See module ModelViewer and ThreeJs for a solution.