<?php
/**
 * @var \Zend\View\Renderer\PhpRenderer $this
 * @var string $style
 * @var string $class
 * @var array $config
 *
 * @link https://github.com/ProjectMirador/mirador/wiki/Configuration-Guides
 */

$configJson = json_encode($config, 320);
$script = <<<JS
$(document).ready(function() {
    $(function() {
        Mirador($configJson);
    });
});
JS;
$this->headScript()->appendScript($script);
?>

<div id="<?= $config['id'] ?>" style="<?= $style ?>" class="<?= $class ?>" allowfullscreen="allowfullscreen"></div>
